POST http://localhost:3333/create/user/v1
Content-Type: application/json

{
    "nome": "Bianca",
    "email": "bia@gmail.com",
    "senha": "123456"
}

###
GET http://localhost:3333/list/users/v1

###
POST http://localhost:3333/login/v1
Content-Type: application/json

{
    "email": "Ana@gmail.com",
    "senha": "ana1234"
}


###
GET http://localhost:3333/user/data/v1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwIiwiaWF0IjoxNzQ0NzMwMTI1LCJleHAiOjE3NDQ3MzEwMjV9.TctRSxwvPeYCj3m85q0ySpzaWsoY3Rquse05FVNaPRA